name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Requirements
        run: |
          pip3 install sphinx-rtd-theme==2.0.0
          pip3 install sphinx-sitemap==2.6.0
          pip3 install sphinxcontrib-spelling==8.0.0
          pip3 install sphinx_rtd_dark_mode==1.2.4
          pip3 install sphinx_reredirects==0.1.3
      - name: Checkout repo
        uses: actions/checkout@1.0.0
      - name: Build docs
        run: |
          make github
          echo 'enginedriver2.mstevetodd.com' > docs/_build/html/CNAME
          touch docs/_build/html/.nojekyll
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: docs/_build/html  # The folder the action should deploy.
